language: node_js
node_js:
- '0.11'
after_install:
- grunt build
deploy:
  provider: cloudcontrol
  email: 'nico.lindemann@proux.de'
  deployment: "fufefe/default"
  skip_cleanup: true
  on:
    branch: master
  password:
    secure: i3vhLik1B0BactRXyFSADBou9cwtytfxFnH1UJwURT4GFrXP9Mg6ri3zzeOeq8LuFLrJ50Izx1Pf/Op6hqH5glHkc3SAfONi5ZkTRuoeXhxPaDeKJNTWmU/nSbwKmSfTZJgMok59ryw7NDaiDjTs3CzcW2z4nztOHn5l6BdeEgc=
